//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_API.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lead
    {
        public System.Guid Uuid { get; set; }
        public string Type { get; set; }
        public string Status { get; set; }
        public string ExpiresAt { get; set; }
        public string CreatedAt { get; set; }
        public string UpdatedAt { get; set; }
        public Nullable<bool> InstantRental { get; set; }
    }
}
