//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_API.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Need
    {
        public System.Guid NeedId { get; set; }
        public string Duration { get; set; }
        public string MoveInDate { get; set; }
        public string TypesOfItems { get; set; }
        public string ReasonForStorage { get; set; }
        public string ReasonForStorage1 { get; set; }
    }
}
